### ISSUE TITLE
Retina Support on Icons

### ISSUE THREAD

**Issue by vinkla** [laravelista/Laranotti#6]
Great plugin you've created! Would be awesome with retina support on the icons. Right now they look a bit blurry on retina displays.

**Comment by mabasic** [comment]
I don't own a retina monitor so it is hard for me to detect, could you be more specific which icons are blurry?

In the popup, notifications, extension bar, chrome store or extension page :) ?

A screenshot would be very helpful, ty

**Comment by vinkla** [comment]
Its in the extension bar I guess. Don't know what it is called. I think you can specify the different sizes in the [manifest.json](http://stackoverflow.com/a/21210020). 

Here is an plugin that has support: https://github.com/sindresorhus/github-notifier-chrome

Screenshot: https://transfer.sh/nLkVy/retina.png

**Comment by mabasic** [comment]
I see what you mean, it is because I converted the `.ico` file from Laracasts to `.png` :) 

It is very small 18x18 I think, and recommended size is 32x32px

Not very proud of it, but I could not find any better logo at that time. 
I plan to update all icons, images, screenshots very soon but for first release it served the purpose.

You are more than welcome to help me update the  icons, I am not so good with design :/

**Comment by vinkla** [comment]
Great! Sure thing, I can help out. I've asked @laracasts [on Twitter](https://twitter.com/vnkla/status/543378061908250624) for assets.

**Comment by mabasic** [comment]
No replies :)

**Comment by vinkla** [comment]
Yeah, to bad :(
